require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@nrwl/react-native/nx_post_install'

platform :ios, '11.0'

target 'Mobile' do
  config = use_native_modules!
  puts config
  use_react_native!(:path => config[:reactNativePath])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable this next line.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|

    flipper_post_install(installer)

    nx_post_install(installer)
  end
end

pod 'GoogleSignIn', '~> 5.0.2'
pod 'RNVectorIcons', :path => '../../../node_modules/react-native-vector-icons'
pod 'RNSVG', :path => '../../../node_modules/react-native-svg'
pod 'react-native-viewpager', :path => '../../../node_modules/react-native-pager-view'
